stages:
  - check

image: golang:1.25.6

check:
  stage: check
  variables:
    PUBLIC_HOME_BASE_URL: "localhost:5173"
    PUBLIC_DASHBOARD_BASE_URL: "localhost:5174"

  script:
    - apt update
    - apt install -y just unzip
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - just check
