stages:
  - sync_repro_build
  - sync_gh_runner
  - check

image: golang:1.25.6

variables:
  GIT_DEPTH: 0

mirror_reproducible_build:
  stage: sync_repro_build
  only:
    - branches
  script:
    - git fetch --all
    - SPLIT_COMMIT=$(git subtree split --prefix=cmd/rep-build)
    - git push https://BenjyRead:${GITHUB_TOKEN}@github.com/BenjyRead/Registry-Reproducible-Builds.git $SPLIT_COMMIT:$CI_COMMIT_REF_NAME --force

sync_runner:
  stage: sync_gh_runner
  only:
    - main
  script:
    - git fetch --all
    - SPLIT_COMMIT=$(git subtree split --prefix=spr-gh-runner)
    - git push https://luddite-ltd:${GH_SYNC_TOKEN}@github.com/luddite-ltd/spr-gh-runner.git $SPLIT_COMMIT:refs/heads/main --force

check:
  variables:
    PUBLIC_HOME_BASE_URL: "localhost:5173"
    PUBLIC_DASHBOARD_BASE_URL: "localhost:5174"

  stage: check

  script:
    - apt update
    - apt install -y just unzip
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - just check
