stages:
  - sync
  - check

image: golang:1.25.6

sync_runner:
  stage: sync
  only:
    - main
  script:
    - git fetch --all
    - SPLIT_COMMIT=$(git subtree split --prefix=spr-gh-runner)
    - git push https://luddite-ltd:${GH_SYNC_TOKEN}@github.com/luddite-ltd/spr-gh-runner.git $SPLIT_COMMIT:refs/heads/main --force

check:
  variables:
    PUBLIC_HOME_BASE_URL: "localhost:5173"
    PUBLIC_DASHBOARD_BASE_URL: "localhost:5174"

  stage: check

  script:
    - apt update
    - apt install -y just unzip
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - just check
