services:
  rabbitmq:
    image: docker.io/rabbitmq:4-management
    ports:
      - "127.0.0.1:7001:15672"
      - "127.0.0.1:5672:5672" # For testing purposes. Comment out in prod.
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_SECRET:-admin}"
  gitea:
    image: docker.gitea.com/gitea:1.25.4
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__security__INSTALL_LOCK=true
      - GITEA_CUSTOM=/data/gitea/custom

    volumes:
      # Uncomment when necessary. No persistence necessary for testing phase
      # - ./data/gitea:/data:Z
      - ./infra/gitea-custom/:/data/gitea/custom:ro
    ports:
      - "127.0.0.1:7002:3000" # TODO: How should we deal with ssh? Necessary?
    entrypoint: ["/bin/sh","-c"]
    command:
      - | # Will run every time on startup but commands are idempotent so no worries
        apk update
        apk add valkey-cli
        cat >> /etc/s6/gitea/setup << 'GITEA_SETUP'
        su-exec git /usr/local/bin/gitea migrate
        su-exec git /usr/local/bin/gitea admin user create \
          --username '${GITEA_ADMIN_USERNAME}' \
          --password '${GITEA_ADMIN_PASSWORD}' \
          --email admin@local \
          --admin \
          --must-change-password=false
        su-exec git /usr/local/bin/gitea admin user generate-access-token \
          --username '${GITEA_ADMIN_USERNAME}' \
          --token-name "spr-admin-token" \
          --scopes "all" | sed "s/^.*: //" >/tmp/spr-admin-token.txt
        valkey-cli -h valkey_db -p 6379 SETNX gitea:tokens:admin "$(cat /tmp/spr-admin-token.txt)"
        GITEA_SETUP
        /usr/bin/entrypoint /usr/bin/s6-svscan /etc/s6
    depends_on:
      gitea_db:
        condition: service_healthy
      minio:
        condition: service_healthy
  minio:
    image: docker.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=internal
      - MINIO_ROOT_PASSWORD=1ts0ktob3ins3cure
      - MINIO_BROWSER_REDIRECT_URL=http://127.0.0.1:7003
    ports:
      - "127.0.0.1:7003:9001"
    # volumes:
      # Uncomment when necessary
      # - ./data/minio:/data:Z
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  gitea_db:
    image: docker.io/library/postgres:18
    restart: always
    environment:
      - POSTGRES_USER=gitea # TODO: Use environment variables
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    # volumes:
      # Uncomment when necessary
      # - ./data/postgres:/var/lib/postgresql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitea -d gitea -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  valkey_db:
    image: docker.io/valkey/valkey:9.0.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${VALKEY_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:
      # Uncomment when necessary
      # - ./data/valkey:/data:Z
  core_db:
    image: docker.io/library/postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=${DB_PASSWORD:-PleaseChangeMe}
      - POSTGRES_DB=secure_registry
    # volumes:
      # Uncomment when necessary
      # - ./data/core_db:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U core -d secure_registry -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
