TEMPLATE: NPM_Containerfile
REPO_URL: https://github.com/sveltejs/prettier-plugin-svelte.git
COMMIT_SHA: f3b7b8b2aa2ed8784c920e7149c2b42528c732a8
OFFICIAL_TGZ_URL: https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-3.4.1.tgz
UNIX2DOS_FILES:
  - LICENSE
  - src/lib/elements.ts
  - src/base64-string.ts
  - src/lib/snipTagContent.ts
  - src/print/doc-helpers.ts
  - src/lib/getText.ts
  - src/lib/extractAttributes.ts

