TEMPLATE: PNPM_Containerfile
NODE_IMAGE: node:23-alpine
REPO_URL: https://github.com/sveltejs/svelte.git
COMMIT_SHA: e1427aa0c8b5abe88aea972ea397ea499cb8f2db
BUILD_DIR: packages/svelte
OFFICIAL_TGZ_URL: https://registry.npmjs.org/svelte/-/svelte-5.48.2.tgz
TGZ_FILENAME: svelte-5.48.2.tgz
ALPINE_IMAGE: alpine:3.23
