# -- Build Stage --
FROM node:23-alpine AS build

RUN apk add --no-cache git pnpm

WORKDIR /app

# Since tags can be moved, we fetch the specific commit instead.
RUN git clone https://github.com/sveltejs/svelte.git .
RUN git fetch --depth 1 origin e1427aa0c8b5abe88aea972ea397ea499cb8f2db
RUN git checkout e1427aa0c8b5abe88aea972ea397ea499cb8f2db

RUN pnpm install --frozen-lockfile
RUN pnpm build --filter ./packages/svelte

# pnpm pack generate tgz file
RUN cd packages/svelte && \
    pnpm pack --pack-destination /out

# Testing diffoscope works
# RUN printf '\n' >> /tmp/svelte-5.48.2.tgz

# -- Pull Stage --
FROM node:23-alpine AS official

RUN apk add --no-cache wget

RUN mkdir -p /out
RUN wget https://registry.npmjs.org/svelte/-/svelte-5.48.2.tgz -O /out/official.tgz

# -- Compare Stage --
FROM alpine:3.23

RUN apk add --no-cache diffoscope

COPY --from=build /out/svelte-5.48.2.tgz /tmp/build.tgz
COPY --from=official /out/official.tgz /tmp/official.tgz

CMD sh -c "\
    set -x; \
    diffoscope /tmp/build.tgz /tmp/official.tgz > /tmp/diffoscope.txt; \
    if [ -s /tmp/diffoscope.txt ]; then \
    echo 'Reproducible Build Test Failed'; \
    echo 'Diffoscope Output:'; \
    cat /tmp/diffoscope.txt; \
    exit 1; \
    else \
    echo 'Reproducible Build Test Passed'; \
    exit 0; \
    fi"
