TEMPLATE: NPM_Containerfile
REPO_URL: https://github.com/microsoft/TypeScript.git
COMMIT_SHA: c63de15a992d37f0d6cec03ac7631872838602cb
OFFICIAL_TGZ_URL: https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz
GITHEAD_INJECTION: true

