TEMPLATE: Yarn_Containerfile
REPO_URL: https://github.com/prettier/prettier.git
COMMIT_SHA: 7584432401a47a26943dd7a9ca9a8e032ead7285
OFFICIAL_TGZ_URL: https://registry.npmjs.org/prettier/-/prettier-3.5.0.tgz
# CUSTOM_YARN: true
# CUSTOM_YARN_PATH: .yarn/releases/yarn-4.6.0.cjs
NODE_IMAGE: node:20-alpine
USE_NPM_PACK: true
CUSTOM_PACK_DIR: dist/
SCRIPTS_FIELD_REMOVAL: true
TAB_SIZE: 2
CHMOD_FILE: true
CHMOD_FILE_PATH: dist/bin/prettier.cjs
