ALTER TABLE "session" DROP COLUMN IF EXISTS "impersonatedBy";

ALTER TABLE "user" DROP COLUMN IF EXISTS "banExpires";
ALTER TABLE "user" DROP COLUMN IF EXISTS "banReason";
ALTER TABLE "user" DROP COLUMN IF EXISTS "banned";
ALTER TABLE "user" DROP COLUMN IF EXISTS "role";
