-- This code is auto generated by better-auth.
-- `bun x auth@latest generate`

CREATE TABLE IF NOT EXISTS "user" (
    "id" text NOT NULL PRIMARY KEY
);

alter table "user" add column if not exists "name" text not null default '';
alter table "user" add column if not exists "email" text not null unique default '';
alter table "user" add column if not exists "emailVerified" boolean not null default false;
alter table "user" add column if not exists "image" text;
alter table "user" add column if not exists "createdAt" timestamptz default CURRENT_TIMESTAMP not null;
alter table "user" add column if not exists "updatedAt" timestamptz default CURRENT_TIMESTAMP not null;
alter table "user" add column if not exists "role" text not null default 'user';
alter table "user" add column if not exists "banned" boolean default false;
alter table "user" add column if not exists "banReason" text;
alter table "user" add column if not exists "banExpires" timestamptz;


create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "activeOrganizationId" text);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" timestamptz not null, "metadata" text);

create table "member" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "userId" text not null references "user" ("id") on delete cascade, "role" text not null, "createdAt" timestamptz not null);

create table "invitation" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "inviterId" text not null references "user" ("id") on delete cascade);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create unique index "organization_slug_uidx" on "organization" ("slug");

create index "member_organizationId_idx" on "member" ("organizationId");

create index "member_userId_idx" on "member" ("userId");

create index "invitation_organizationId_idx" on "invitation" ("organizationId");

create index "invitation_email_idx" on "invitation" ("email");

-- Seed default admin user (password: Admin1234!)
INSERT INTO "user" ("id", "name", "email", "emailVerified", "role", "createdAt", "updatedAt")
VALUES ('seed-admin-1', 'Admin', 'admin@admin.com', TRUE, 'admin', NOW(), NOW())
ON CONFLICT ("email") DO NOTHING;

INSERT INTO "account" ("id", "accountId", "providerId", "userId", "password", "createdAt", "updatedAt")
VALUES ('seed-admin-account-1', 'admin@admin.com', 'credential', 'seed-admin-1', '59a0cd2dffa80a11bcfe29d704231915:f01cc43f77d2ce7e7b4bd5657c12c24de28f164c849ce26471b218b0ba82a25524299037934968fab1be8fc65ed268d953344f8ceef9ba2c46f4fa32c0f0eba3', NOW(), NOW())
ON CONFLICT ("id") DO NOTHING;
