# Build stage
FROM docker.io/oven/bun:1 AS builder
WORKDIR /app

ARG PUBLIC_DASHBOARD_BASE_URL
ENV PUBLIC_DASHBOARD_BASE_URL=${PUBLIC_DASHBOARD_BASE_URL}

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

# Production stage
FROM docker.io/oven/bun:1-slim AS release
WORKDIR /app

COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

EXPOSE 3000
EXPOSE 3000

CMD ["caddy", "file-server", "--root", "/srv", "--listen", ":3000"]
CMD ["bun", "./build/index.js"]
